# Generated by Django 2.1.7 on 2019-03-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(blank=True, db_index=True, max_length=40)),
                ('sha1', models.CharField(blank=True, db_index=True, max_length=50)),
                ('disk_size', models.BigIntegerField()),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('path', models.CharField(max_length=4000)),
                ('filename', models.CharField(max_length=1000)),
            ],
        ),
    ]
